# Generated by Django 4.0.9 on 2023-11-14 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('suburb', models.CharField(max_length=255, verbose_name='Suburb')),
                ('is_for_sale', models.BooleanField(default=False, verbose_name='For sale')),
                ('is_for_lease', models.BooleanField(default=False, verbose_name='For lease')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('leased', 'Leased'), ('deleted', 'Deleted')], default='available', max_length=20, verbose_name='Status')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'real_estate_properties',
            },
        ),
    ]
