# Generated by Django 4.0.9 on 2023-03-05 09:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=500)),
                ('price', models.FloatField(default=0.0)),
                ('is_lease', models.BooleanField(default=False)),
                ('is_suburb', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('LEASED', 'Leased'), ('DELETED', 'Deleted')], default='AVAILABLE', max_length=10)),
            ],
            options={
                'db_table': 'property_res',
            },
        ),
    ]
