# Generated by Django 4.0.9 on 2023-03-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0003_alter_property_created_by_alter_property_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
